import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen text-text-light flex flex-col items-center font-inter">
          <Header />
          <main className="p-10 flex flex-col items-center gap-8 w-full max-w-6xl flex-grow">
            <section className="w-full flex flex-col items-center flex-grow">
              <div className="flex items-start w-full">
                {children}
                </div>
            </section>
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
